### ISSUE TITLE
View should change size when keyboard is shown

### ISSUE THREAD

**Issue by zzt4** [mattermost/ios#11]
The View should change it's size when the keyboard is shown. When the keyboard is shown, you lose the interface buttons at the top of the screen since it is pushed off-screen. Right now the only way to get those buttons back is to either scroll all the way up to the top of all of the messages, or to hide the keyboard.

**Comment by lfbrock** [comment]
Tracking this issue in Jira: https://mattermost.atlassian.net/browse/PLT-2460
