### ISSUE TITLE
iOS Mattermost app should be able to connect to more than one team / server

### ISSUE THREAD

**Issue by PSchwarck** [mattermost/ios#12]
Right now the mattermost iOS app can connect to a single team / server. But for some use case (bigger Enterprise, several different servers) the iOS should support this as well.

**Comment by sadortun** [comment]
Also, it seems that we cant switch between team s while in the app using GitLab SSO

**Comment by lfbrock** [comment]
You can upvote this feature here: https://mattermost.uservoice.com/forums/306457-general/suggestions/10975938-ios-app-should-allow-multiple-connections
