### ISSUE TITLE
False Positive: Invalid certificate

### ISSUE THREAD

**Issue by pdnellius** [mattermost/ios#13]
Mattermost for iOS is returning "certificate for this server is invalid" under the team URL box. This is a signed TLS1.2 cert that should be working. Including a screenshot from chrome inspector via web:

![screen shot 2016-02-18 at 11 11 12 am](https://cloud.githubusercontent.com/assets/5667111/13149753/aba80eb4-d630-11e5-8899-743910d99f37.png)

**Comment by pdnellius** [comment]
![img_1004 copy](https://cloud.githubusercontent.com/assets/5667111/13149854/14adc548-d631-11e5-995f-19f4793f7f29.png)

**Comment by rennhak** [comment]
+1

**Comment by dmigous** [comment]
+1

**Comment by lfbrock** [comment]
Created a ticket in [Jira](https://mattermost.atlassian.net/browse/PLT-2169) to track this issue.

**Comment by rennhak** [comment]
Thanks!
