### ISSUE TITLE
Caching old messages in mobile App? (like slack, whatsapp etc...) + add (configurable) connection time out.

### ISSUE THREAD

**Issue by PSchwarck** [mattermost/ios#14]
When starting the iOS App 2.0, the app is syncing its data. This usually takes quite a while. Another thing is, that when the device is "offline" (e.g. flightmode), I'm not able to read my already received messages on my mobile app. When Offline and the app gets started, It looks like there is no time out set, when no internet connection (circle keeps spinning since minutes). Could you cache the the data and just sync "new" messages? I just checked slack app and they offer this, which is quite helpful.

**Comment by PSchwarck** [comment]
https://mattermost.uservoice.com/forums/306457-general/suggestions/12471465-caching-old-messages-in-mobile-app-like-slack-w

**Comment by lfbrock** [comment]
Closing issue, please upvote feature request here: https://mattermost.uservoice.com/forums/306457-general/suggestions/12471465-caching-old-messages-in-mobile-app-like-slack-w
