### ISSUE TITLE
Photo's taken on iPhone 6S Plus are too large to be sent/attached.

### ISSUE THREAD

**Issue by jaapvdv** [mattermost/ios#15]
Error: 
Unable to upload file. File is too large.

Sending images photo library, taken on previous phones or different camera's is no problem.

Turning live photo's off, or using an app like Lively (selecting one frame to send/share) works fine.

iPhone 6S Plus / iOS 9.2.1

**Comment by esethna** [comment]
Thanks for bug report @jaapvdv. We are investigating. [Ticket can be tracked in JIRA](https://mattermost.atlassian.net/browse/PLT-1964).
