### ISSUE TITLE
When opening an attachment in iOS-App, Error message 'You do not have the appropriate permissions'

### ISSUE THREAD

**Issue by PSchwarck** [mattermost/ios#16]
When opening an attachment via 'download' in iOS-App, Error message 'You do not have the appropriate permissions', when using 'get public link' the attachments gets opened in safari. 

{"id":"api.context.permissions.app_error","message":"You do not have the appropriate permissions","detailed_error":"userId=","request_id":"y1poxduqtjnktj8u5rm1n8ankr","status_code":403,"is_oauth":false}

**Comment by lfbrock** [comment]
This should be fixed now.
