### ISSUE TITLE
Modal missing when trying to pick theme colors

### ISSUE THREAD

**Issue by frdmn** [mattermost/ios#17]
I just discovered a little bug on the iOS app. When you try to open the color picker to choose a color from for a custom theme and you focused one of the text areas before (tap into them), the whole theme modal disappears and the only thing left shown is the actual color picker:

I tried to reproduce the problem in the [yuya-oc/electron-mattermost](https://github.com/yuya-oc/electron-mattermost) as well as in the web version, but it doesn't occur there. Checkout the following demos:

---

### iOS (problem case)

![mattermost-ios mov-small](https://cloud.githubusercontent.com/assets/944459/13457148/dd39e5b6-e066-11e5-97f2-e6324056db9b.gif)

### Mac app (no problem)

![mattermost-mac mov](https://cloud.githubusercontent.com/assets/944459/13457117/aad3207e-e066-11e5-80e0-e30f8ac84b8c.gif)

**Comment by lfbrock** [comment]
I think this has been fixed, can't reproduce on the latest version.

**Comment by frdmn** [comment]
Nope, can't reproduce either :+1:
