### ISSUE TITLE
default app via public appstore

### ISSUE THREAD

**Issue by joernhees** [mattermost/ios#2]
It's cool to see that there now seems to be an app and that it's even open source :+1:, but self-compiling seems like an enormous hurdle that only relatively few teams will (be able to) take. Lacking the iOS dev knowledge (and time to acquire it), I'd be willing to trust you guys and use a default app from the public AppStore (and even pay a couple EUR for it)...

If you need this to properly encrypt push messages (as it seems to me) or to deliver push notifications at all, by no means remove this option to self compile, but have a ready to use fallback for easier adoption and smaller / non-iOS dev teams...

Maybe like Threema: don't send the message via push notification but just an ID that something happened... once the app is activated it can fetch the message securely.

**Comment by coreyhulen** [comment]
The app is now in the app store.

**Comment by joernhees** [comment]
not for me... 

![img_3016](https://cloud.githubusercontent.com/assets/464192/12093687/9d8b7cd4-b304-11e5-8fd4-e3f3a9b9195f.PNG)

**Comment by coreyhulen** [comment]
I've re-opened the issue.

I'm guessing you're in a non-US app store?  We're in the process of submitting to all countries.

**Comment by joernhees** [comment]
ah ok, i'm in the german app store...

and it is available now... thanks a lot ;)
