### ISSUE TITLE
Gitlab Connect redirect to Safari and never returns

### ISSUE THREAD

**Issue by sadortun** [mattermost/ios#22]
Hi,

When logging in with Gitlab Connect, the gitlab login is done in Safari, and then Safari il redirected to Mattermost team page URL, but never say return to the App. 

When returning to the app manually, the login screen is shown again

**Comment by Korni22** [comment]
Have you tried reinstalling the application?

One of our user had this problem and it was solved by reinstalling the app 👍

**Comment by sadortun** [comment]
> Have you tried reinstalling the application?
I just did, and it working correctly now. 

Thanks!

**Comment by GhostLyrics** [comment]
Worked for me too.
*Hopefully this is not a reoccurring problem.*

**Comment by sadortun** [comment]
@Korni22 @GhostLyrics sadly, it looks a recurring problem :(

I was able to connect to a first team this morning, but when switching team I had the same issue.

**Comment by sadortun** [comment]
I've done a few more tests. 

Logging out, changing the team URL and logging back is working.
Switching teams using the menu doesn't work and redirect to Safari

**Comment by lfbrock** [comment]
Hi @sadortun, switching teams on mobile should be fixed in Mattermost v3.0 (releasing May 16th). If you hit this issue on v3.0, please re-open?

**Comment by sadortun** [comment]
Wow, they are going to run out of major version fast if they already jump to 3.x ! Thanks!
