### ISSUE TITLE
app gets 404 for http://107.170.37.135/api/v3/users/initial_load against a 2.2 server

### ISSUE THREAD

**Issue by cloudmode** [mattermost/ios#23]
app gets 404 for http://107.170.37.135/api/v3/users/initial_load against a 2.2 server.

running the mattermost/mattermost-docker server on ubuntu 14. getting 404 not found returned by the server. according to the github repository, the server was upgraded to 2.2.0 8 days ago. Is there an upgrade required for the ios app too?

thanks in advance.

**Comment by it33** [comment]
Hi @cloudmode, sorry, we forgot to add a warning that iOS is being overhauled to work with [Mattermost 3.0 server](http://www.mattermost.org/upgrading-to-mattermost-3-0/), which has new APIs and won't work with 2.x, you can recompile using the 2.0 release tag and it should work again.
