### ISSUE TITLE
Edit post menu out of view

### ISSUE THREAD

**Issue by mackelito** [mattermost/ios#24]
Clicking edit on the last post makes the menu end up outside view

**Comment by lfbrock** [comment]
Hi @mackelito, can you check what version of Mattermost you are on from Main Menu > About Mattermost on a web browser (not the iOS app)?

**Comment by mackelito** [comment]
Mattermost Team Edition

Version:2.2.0
Build Number:6671
Build Date:Fri Apr 15 18:40:19 UTC 2016
Build Hash:8e883ad2f516820942cc0131241268c1ea909ff3

**Comment by lfbrock** [comment]
Thanks @mackelito, just tested this and I think it's fixed in v3.0 which will be released May 16th. If you run into the issue on v3.0 please reopen?
