### ISSUE TITLE
Not a complaint!

### ISSUE THREAD

**Issue by mackelito** [mattermost/ios#25]
The iOS app is written i swift with is cool and all... but I see that the desktop app is done with electron so I was just wondering if you guys have looked at Ionicframework for the apps?

**Comment by mackelito** [comment]
Note: This is a egoistic request actually... because I want to be able to contribute! ;)

**Comment by lfbrock** [comment]
Hi @mackelito, no I don't think we looked at using electron for the apps - I think the goal is to eventually move to completely native apps, but this isn't planned for the near future. 

The forums might be a better place to discuss questions like this: forum.mattermost.org

**Comment by mackelito** [comment]
Ah ok... cool... I´ll have a look around in the forum 👍 

Just to clarify.. 
Electron = Desktop apps
Ionic = Mobile apps
