### ISSUE TITLE
iOS app renders screen with blank boxes instead of text

### ISSUE THREAD

**Issue by fjarlq** [mattermost/ios#27]
#### Summary
Upon opening the iOS app, blank boxes are seen where the conversation text should be.

#### Steps to reproduce
1. Install the iOS Mattermost app version 3.0 onto an iPhone 6s running iOS 9.3.2. (I haven't tested other iOS devices)
2. Connect the app to a Mattermost server version 3.0.2 and log in.
3. Open the app.
4. Rarely, observe the app rendering blank boxes instead of text.
5. Note that there is no obvious way to resolve the problem. The user just sees a screen showing empty boxes and some avatars.
6. Note that the problem is not fixed by waiting a full minute.
7. Note that the problem is not fixed by returning to the home screen and then reopening the app.
8. Note that the problem is fixed by killing and reopening the app (ie. double-pressing the home button and swiping up the open app).

#### Expected behavior
I expect the app to always display the conversation text when I open it, or to at least display an error explaining why it couldn't after at most 10 seconds have elapsed.

#### Observed behavior
I've only seen this happen once so far. But, I haven't opened the iOS app more than about 15 times, ever. (I'm not in the habit of using it, yet.) This is the screen I saw when I opened the app:
![ios-renderbug1](https://cloud.githubusercontent.com/assets/441483/15615987/701173ce-23fe-11e6-8a5b-3bfdf842ac94.png)

**Comment by lfbrock** [comment]
Hi @fjarlq, we've been keeping an eye out for this issue, but haven't been able to reproduce it yet. 

If anyone else from the community is seeing this, please post here and let us know?

**Comment by lfbrock** [comment]
Closing this issue, if people are still seeing it please reopen.
