### ISSUE TITLE
Support gitlab/SSO authentification

### ISSUE THREAD

**Issue by faroit** [mattermost/ios#3]
Mattermost supports authentification through [single-sign on via Gitlab](http://forum.mattermost.org/t/preview-ldap-sso-support/211). It seems like the iOS app currently is unable to redirect to gitlab for authentification. 

Can this be supported maybe through a modal webkit sheet?

**Comment by ewjoachim** [comment]
For now, it's not only that we can't use the Gitlab SSO on the app, but we can't even login because mattermost won't allow creating a password for direct access when GitLab SSO is activated :/

**Comment by it33** [comment]
Working on adding this, sorry it didn't make it in the first release,

**Comment by ewjoachim** [comment]
Sorry for sounding harsh ^^' Thanks for your amazing work, mattermost is a really nice project, and I can't wait toseewhat's coming next :)

**Comment by heikobornholdt** [comment]
Hello, I'm also interested in SSO through GitLab :+1:

**Comment by pdnellius** [comment]
Love the product, can't wait for SSO via GitLab!

**Comment by GhostLyrics** [comment]
Is this also in the post gitlab-8.5 release?

**Comment by it33** [comment]
Yes, the Mattermost release in GitLab 8.5 will support the Mattermost iOS app with GitLab SSO

**Comment by yuters** [comment]
Yeah I just installed this today and the redirect seems to work with Gitlab 8.5.

However... when you have Two-Factor Authentication on Gitlab: if you leave the application to go look for the code in Google Authenticator and come back in Mattermost, the modal for the login disappears and you have to start over.

Then you have to beat the clock and get back to that point under the 30 sec when the code is valid. :D

**Comment by it33** [comment]
Thanks @yuters, thanks to all for the feedback!
