### ISSUE TITLE
First Time Login Process jumps bag an app switch

### ISSUE THREAD

**Issue by nik-ffm** [mattermost/ios#31]
I try to log into my companies mattermost. Therefore I need the two-factor authentication and this is working using Google Authenticator. So after the login using GitLab it asks me two enter the code. I switch the app the google authenticator, copy the number and switch back to the mattermost app. At that point the app jumps back to the first login screen, so I can't enter my two-factor code. This makes it impossible to login the first time using 2-factor auth per some different app on the same phone.

**Comment by lfbrock** [comment]
Hi @nik-ffm, what version of Mattermost/the iOS app are you using? Can you see if this still happens with the latest version of the app? 

Also I don't think Mattermost MFA is supported with GitLab, there should be MFA on your GitLab account directly?

**Comment by nik-ffm** [comment]
@lfbrock I'm using the newest version and still have the same problem - but I found a way to get it running. I just copies and key before going to mattermost and than hurried a bit to get the login done...

**Comment by lfbrock** [comment]
Thanks @nik-ffm, I was able to reproduce it on master. 

I filed a ticket here to track the issue: https://mattermost.atlassian.net/browse/PLT-3716

I'm going to close this GitHub issue + we'll track the bug in Jira
