### ISSUE TITLE
SSO with GitLab no longer works

### ISSUE THREAD

**Issue by jakespencer** [mattermost/ios#36]
When using the Mattermost bundled with GitLab the sign in with GitLab button leaves the app and opens in Safari so you are unable to sign in via the iOS app.

I don't believe this is an issue with GitLab/Mattermost server as on Android it is fine.

**Comment by GhostLyrics** [comment]
This issue can be worked around by (sometimes) waiting for some time to let some timeout trigger and logging in again. It definitely can be worked around by reinstalling the app.

I sporadically have the same issue but don't know how to reproduce it reliably.

**Comment by lfbrock** [comment]
@jakespencer, what version of the iOS app and Mattermost server are you on? 

There's a new v3.3 iOS app that was just released, can you:
1) Try using the v3.3 iOS app that just released
2) Try creating an account on gitlab.mattermost.com, and test if the app works with that? 

I just tested with gitlab.mattermost.com and it seemed to be working fine for me.

**Comment by jakespencer** [comment]
@lfbrock I took @GhostLyrics advice which worked, so can't really confirm if the update solves the issue or not. I suspect it is something to do with the login expiring on Mattermost which is set to 30 days at the moment and then some kind of session data left behind on the client which breaks stuff but I have not had a chance to look into it really.

**Comment by InterHmai** [comment]
Hey, I still see this with 3.4.0. It's pretty frustrating and generally happens when your connection goes out while opening the app after you are already logged in. I want to also say it occurs after your session credentials have expired.

**Comment by lfbrock** [comment]
Hi @InterHmai, I was able to reproduce this happening after the session credentials expire, thanks for the clear repro.

I made a ticket here for someone to look into the issue: https://mattermost.atlassian.net/browse/PLT-4349

**Comment by JJJ** [comment]
> Pretty sure it reliably occurs after your session credentials have expired.

This is my experience, also. To be clear, it's after the Mattermost session has expired. It makes no difference if your GitLab session is still good or not.

1. If your GitLab session is not good, you'll see the GitLab sign-in screen
1. If your GitLab session is good, you'll see the Mattermost teams screen

**Comment by wrbluepearl** [comment]
I'm also seeing this problem - pretty frustrating, though deleting/reinstalling the application does seem to "fix" the problem for me.
