### ISSUE TITLE
Screen stays all white after startup  (iOS 10 beta)

### ISSUE THREAD

**Issue by abcdev** [mattermost/ios#37]
I have noticed that in the latest iOS 10 betas (iPhone 5s) the screen stays white after startup.
Reinstalling the app helps up to point 3 mentioned below... this is a big pain

Steps to reproduce:
  1. Fresh install of the the app
  2. Sign in to a server and have a chat
  3. Restart iPhone or forcefully close the app
  4. Open app again

**Comment by it33** [comment]
Hi @abcdev, 

We're having difficult reproducing the issue. Could we ask your help to create an account on pre-release.mattermost.com and see if it happens there?

**Comment by abcdev** [comment]
This issue stopped occurring after we moved from a self-signed to an "officially" signed one. The Server is running CentOS 6, Apache 2.4 (self-signed cert). MySQL 5.7.14.
