### ISSUE TITLE
Sending without using Enter is annoying

### ISSUE THREAD

**Issue by KittBlog** [mattermost/ios#39]
Currently you can’t use Enter/Return to send a message in the native app. This is really annoying and different to any other app I know (Messages, Slack, HipChat, Hangouts, WhatsApp and so on…). 

I would highly recommend to change this behavior as sending a message easily is much more important than create a new line on mobile devices.

**Comment by lfbrock** [comment]
Hi @KittBlog - I think that Enter does create a new line in Whatsapp and iMessage (on iOS10).

That being said, maybe we could add a setting to control the behaviour on our [new mobile apps](https://forum.mattermost.org/t/fyi-project-underway-to-increase-mobile-app-performance-on-slow-internet-connections-using-react-native/2219). If you'd like to open a [feature suggestion](https://www.mattermost.org/feature-ideas/) outlining how it should work, we can consider adding it after the basic framework for the apps is done.

**Comment by jasonblais** [comment]
@KittBlog, if you're interested [opening a feature suggestion](https://www.mattermost.org/feature-ideas/), the idea can be upvoted, discussed and prioritized with the community.

Each member gets 10 votes on the feature idea forum, influencing the future of the Mattermost software.
