### ISSUE TITLE
adding support for htaccess in front of mattermost

### ISSUE THREAD

**Issue by rejozenger** [mattermost/ios#4]
This is a feature request, not a bug report.

It'd be nice if the iOS application would be able to handle an htaccess in front of Mattermost. I have Mattermost running nicely and browsers on both desktop and mobile platforms (obviously) interact correctly with htaccess configured to protect the Mattermost interface. If the users wants to access the interface, the browsers prompts the user for the htaccess username and password first, then proceeds with the Mattermost interface. The iOS applications fails with a generic error.

**Comment by lfbrock** [comment]
Hi @rejozenger, 

Could I have your help [contributing a feature request](http://www.mattermost.org/feature-requests/) on this?
