### ISSUE TITLE
any plan to joing appconfig.org

### ISSUE THREAD

**Issue by jimiatworking** [mattermost/ios#40]
Hi, I would like to know that does there any plan to make mattermost support AppConfig (http://appconfig.org/) that we could configu for Enterprises use. e.g: EMM support.

**Comment by lfbrock** [comment]
Hi @jimiatworking - there's no plans at this point in time, would you be willing to add a [feature request](https://www.mattermost.org/feature-ideas/) for it so we can see if it's something other people need as well?

**Comment by jasonblais** [comment]
Would you like to [contribute this in the feature idea forum](https://mattermost.uservoice.com/forums/306457-general/) so it can be discussed, upvoted and considered for a [ticket accepting pull requests](http://docs.mattermost.com/process/accepting-pull-request.html)?

Please include a link back to this GitHub Issue. If you're interested in implementing, please say so and we'll prioritize the review. 

You get **10** votes in the feature idea forum, and each one influences the future of the project.

Closing this issue on the GitHub repository, given it's not a product defect.
