### ISSUE TITLE
proxy settings ios app

### ISSUE THREAD

**Issue by rkopplin** [mattermost/ios#44]
Hello,

is there a way to set up proxy settings + port to connect to the mattermost server URL?
Maybe in a future update?

Many thanks

**Comment by lfbrock** [comment]
Hi @rkopplin - not sure what you mean here? Can you explain some more?

**Comment by rkopplin** [comment]
its possible to use a http proxy server in some apps to define url / port and authentification to connect via this setup to some network.

our mattermost application is only internal so there isnt a way to connect without a proxy server to our network  and use the mattermost app.

http://stackoverflow.com/questions/32435074/ios-http-proxy-setting-api

**Comment by yangchen1** [comment]
Hey @rkopplin - you can't do this though the app, unfortunately! You should be able to send your traffic though a proxy in iOS though. In the meanwhile, feel free to send a feature request on our [UserVoice](https://mattermost.uservoice.com)!

**Comment by jasonblais** [comment]
Hey again @rkopplin, appreciate your feedback  

Would you like to [contribute this in the feature idea forum](https://mattermost.uservoice.com/forums/306457-general/) so it can be discussed, upvoted and considered for a [ticket accepting pull requests](http://docs.mattermost.com/process/accepting-pull-request.html)?

Please include a link back to this GitHub Issue. If you're interested in implementing, please say so and we'll prioritize the review. 

You get **10** votes in the feature idea forum, and each one influences the future of the project.
