### ISSUE TITLE
Support for custom notification sounds

### ISSUE THREAD

**Issue by elyscape** [mattermost/ios#45]
If an app doesn't provide any custom notification sounds, all notifications for the app use the default Tri-tone sound. It would be nice if the app offered a choice of notification sounds.

**Comment by lfbrock** [comment]
Hi @elyscape - can you make a feature request for this on our [feature request forums](https://mattermost.uservoice.com/forums/306457-general)? 

We're working on a new mobile app at the moment, so it's probably easiest to track this as a feature request and then look at adding it in the new mobile apps.

**Comment by elyscape** [comment]
[Done](https://mattermost.uservoice.com/forums/306457-general/suggestions/17213822-use-custom-notification-sound).

**Comment by yangchen1** [comment]
Great, thank you @elyscape!
