### ISSUE TITLE
Support for IOS 8.x

### ISSUE THREAD

**Issue by thos37** [mattermost/ios#46]
I am attempting to get a group to use Mattermost, but one person is running iOS 8.x.  Is there any reason why the app in the app store is 9.x and up?  I tried building it for 8.x and it appears to run ok. ...

**Comment by lfbrock** [comment]
Hi @thos37 - we're only able to support and test iOS 9+, I don't think anyone has tested on iOS 8 to confirm what works or doesn't work. I think iOS 8 makes up <2% of the market share for iPhones, so I'm not sure if it's something we'll add support for at this point in time.
