### ISSUE TITLE
Application stuck if the server is down

### ISSUE THREAD

**Issue by MartinDelille** [mattermost/ios#48]
If the server previously configured for the application is down, launching it leads to this screen:

![2016-11-16 18 07 41](https://cloud.githubusercontent.com/assets/879889/20357350/e7c1fbf8-ac27-11e6-935c-48f4973c97cd.png)

In my case I had changed the server URL and the only way to change the URL was to erase the application and install it again.

Maybe there should be a better fallback in this case.

**Comment by yangchen1** [comment]
Hey @MartinDelille, thanks for reporting it! We'll track this issue in JIRA:

https://mattermost.atlassian.net/browse/PLT-4837

**Comment by MartinDelille** [comment]
<img width="532" alt="capture d ecran 2016-12-01 a 14 24 00" src="https://cloud.githubusercontent.com/assets/879889/20795525/e7f7d876-b7d1-11e6-8a69-d9f7d8406957.png">

**Comment by enahum** [comment]
Sorry @MartinDelille I made the ticket public

**Comment by jasonblais** [comment]
Thanks again @MartinDelille, I'll close this issue and we can track the issue in JIRA: https://mattermost.atlassian.net/browse/PLT-4837
