### ISSUE TITLE
iOS App: no auto scrolling of the chat history inside the channel (new posts aren't visible without scrolling)

### ISSUE THREAD

**Issue by finius** [mattermost/ios#5]
When having a channel open and recieving/sending a new post, this new post is inserted below the textbox. So it is unreadable/unseeable without scrolling the screen. With every new post one has to scroll to read the new entries (even the own), because it's inserted below the TextBox.
One could say, that no auto scrolling of the chat history is currently available which is very hard in longer conversations on the mobile.

**Comment by lfbrock** [comment]
Hi @finius, 

Just to confirm, this is when you are scrolled up in a channel and a new message comes into the same channel?

We have a [Jira ticket](https://mattermost.atlassian.net/browse/PLT-1917) to add a "New Messages" indicator when there are new messages below, would this solve your issue?

**Comment by finius** [comment]
Yes, I think so. But the channel should not auto scroll down when a new message came in. That would be very annoying.But some kind of hint or popup where one can click on if wanted to jump to the latest entry would be cool.

**Comment by PSchwarck** [comment]
Hm. On top of a highlight, that new messages are coming in, I prefer that that conversation scrolls, WHEN I am already on the latest message. When I'm not there yet, it freaks me out, when I am automatically put to the latest message, and have to scroll up again. To me this behavior depends on, where I am currently reading. What do you think?

**Comment by lfbrock** [comment]
I think what @PSchwarck described is the existing behaviour. If you are at the bottom of the channel, the view scrolls to show new messages and if you are not at the bottom of the channel, your view should stay where it is.

The new feature would keep the existing behaviour, but would add a floating indicator to show there are new messages below. So @finius, it would not automatically scroll to the new message. 

Closing this issue, and will track adding the floating indicator in Jira.

**Comment by finius** [comment]
Great, Thanks!
