### ISSUE TITLE
Empty name on notifications

### ISSUE THREAD

**Issue by AimenJoe** [mattermost/ios#52]
When we get the notification, the name is blank.
I can only assume the reason, that might be related with encoding.
Only the name is the changeable part in the payload. This is why I think this issue caused from the encoding.
In my case, the name was Korean characters.
Can you please check this out?

I'm aware of that this is not from the mobile app part, but the server-side. However, it is also needed to cooperate, right? So I'm reporting this issue here.

Thank you! 😄

**Comment by lindy65** [comment]
Hi @AimenJoe,

I have tried to reproduce the issue on iOS but wasn't able to.  

Could you tell me which name field you are referring to (e.g. username, nickname, etc.) that does not appear in the push notification?

Please also let me know whether changing that name field to English characters reproduces the same error for you.

Thanks!

**Comment by AimenJoe** [comment]
Thank you for your response, @lindy65 

Sorry for making you confused.
It seems the problem of integration of gitlab. The name comes from the gitlab triggered messages.
Other messages are coming without problem (it shows username correctly).
But the gitlab triggered message omitted the name field if it's not english characters.
I don't know who should handle this issue, Mattermost or Gitlab..
You could close this issue cuz it's obviously not from iOS app side.
Anyway!

Thank you!

**Comment by lindy65** [comment]
Hi @AimenJoe,

If it seems to be a GitLab integration problem, you could try posting your issue to the [GitLab Troubleshooting Forum](https://forum.gitlab.com/c/troubleshooting) where you might find some answers?
