### ISSUE TITLE
Swift 3 / Xcode 8 Support

### ISSUE THREAD

**Issue by PrestonL** [mattermost/ios#54]
This branch hasn't been updated for Swift 3 / Xcode 8 # # @

**Comment by PrestonL** [comment]
I have converted the project and fixed issues, this fork compiles and works, additional testing is required, but it seems to compile/run fine.  A few issues are mentioned in the pull request.

https://github.com/mattermost/ios/pull/55

**Comment by coreyhulen** [comment]
Thanks for the PR I think it's worth upgrading the code base to the latest swift/xcode.  This might take us a while to review and merge.  We've been focused on the new apps and the old apps are only receiving minimal support at the moment.
