### ISSUE TITLE
no support for LDAP authentification yet

### ISSUE THREAD

**Issue by finius** [mattermost/ios#6]
When trying to login to an RC Version of Mattermost Enterprise Edition 1.3 (Build Number: ent-rc1-2) no authentification is possible if Mattermost expects LDAP credentials.

**Comment by GhostLyrics** [comment]
Seems to be implemented and merged into master with 5acc8b66ffd764ce677a888c9fbbe4e7ea0a8816.

**Comment by it33** [comment]
It's in but not released, requires a change to Mattermost server that's coming out with Feb 16th release, once that is in, we can create a new release for iOS

**Comment by youknowjack** [comment]
Will the Feb 16th release support logging in through gitlab? We are piloting Mattermost with the gitlab-based login. (Our gitlab login is LDAP-based, FWIW.)

**Comment by GhostLyrics** [comment]
@youknowjack same situation here. Do you have mattermost as part of gitlab-omnibus?

**Comment by youknowjack** [comment]
@GhostLyrics yep... http://doc.gitlab.com/omnibus/gitlab-mattermost/

**Comment by it33** [comment]
LDAP/AD SSO (with pre-released Enterprise Edition) and GitLab SSO work if you compile `master` on the app and the server. 

There is a breaking change to mobile APIs, so SSO needs the Mattermost server shipping Feb 16 before the reference implementation of the iOS app can be pushed to iTunes. 

See [changelog](https://github.com/mattermost/ios/blob/master/CHANGELOG.md) for details.
