### ISSUE TITLE
iOS client should (like the website itself) connect automatically to first and only existing team on a server

### ISSUE THREAD

**Issue by finius** [mattermost/ios#7]
When opening a mattermost server main page (highest level website / team creation page) it shows directly the login to the one and only existing Team site, if  "Include this team in the Team Directory" inside the Teams Settings is set to "Yes" and inside the Teams Settings section of the System Console, the "Enable Team Directory" is set to true. 
This is a smart behaviour and would pretend only one-teamed organisations to enter a specific team subsite name when creating the teams app login on the phone.

**Comment by mackelito** [comment]
I agree that this would be a good feature! We are a company of 250-300 ppl and our setup is one team in mattermost but then each team has it´s own channel.

Post a request here https://mattermost.uservoice.com/forums/306457-general

**Comment by it33** [comment]
Jira ticket opened to track this: https://mattermost.atlassian.net/browse/PLT-2934

Mobile apps in 3.0 can now connect to multiple teams, the work remaining is to auto-select a team if a user only has one team. 

Closing this ticket so we can track in Jira.

**Comment by mackelito** [comment]
Is there a way to track in your jira? Or do I have to create an account?

**Comment by it33** [comment]
You need to create an account,

**Comment by mackelito** [comment]
😢
